routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use UniSharp\LaravelFilemanager\Lfm;
use App\Http\Controllers\Front\{
    PostController as FrontPostController,
    CommentController as FrontCommentController,
    ContactController as FrontContactController,
    PageController as FrontPageController
};
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => 'auth'], function () {
    Lfm::routes();
});

//ensemble de routes qui concerne les posts
Route::prefix('posts')->group(function () {
    Route::name('posts.display')->get('{slug}', [FrontPostController::class, 'show']);
    Route::name('posts.search')->get('', [FrontPostController::class, 'search']);
    Route::name('posts.comments')->get('{post}/comments', [FrontCommentController::class, 'comments']);
    Route::name('posts.comments.store')
        ->post('{post}/comments', [FrontCommentController::class, 'store'])->middleware('auth');
    
});

//Ensemble de routes qui dispose l'intérieur du layout???
Route::name('home')->get('/', [FrontPostController::class, 'index']);
Route::name('category')->get('category/{category:slug}', [FrontPostController::class, 'category']);
Route::name('author')->get('author/{user}', [FrontPostController::class, 'user']);
Route::name('tag')->get('tag/{tag:slug}', [FrontPostController::class, 'tag']);
Route::name('front.comments.destroy')->delete('comments/{comment}', [FrontCommentController::class, 'destroy']);
Route::name('page')->get('page/{page:slug}', FrontPageController::class);

//Ressource partielle
Route::resource('contacts', FrontContactController::class, ['only' => [
    'create',
    'store'
]]);

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Http/Controllers/Front/CommentController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Front\CommentRequest;
use App\Models\{ Comment, Post };

class CommentController extends Controller
{
    public function __construct()
    {
        if(!request()->ajax()) {
            abort(403);
        }
    }

    public function store(CommentRequest $request, Post $post)
    {        
        $data = [
            'body' => $request->message,
            'post_id' => $post->id,
            'user_id' => $request->user()->id,
        ];

        $request->has('commentId') ?
            Comment::findOrFail($request->commentId)->children()->create($data):
            Comment::create($data);

        $commenter = $request->user();

        return response()->json($commenter->valid ? 'ok' : 'invalid');
    }

    public function destroy(Comment $comment)
    {
        $this->authorize('delete', $comment);
        $comment->delete();

        return response()->json();
    }

    /**chargement des commentaires pour un Post */
    public function comments(Post $post)
    {
        $comments = $post->validComments()->withDepth()->latest()->get()->toTree();

        return [
            'html' => view('front/comments', compact('comments'))->render(),
        ];
    }
}

app/Http/Controllers/Front/ContactController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Http\Requests\Front\ContactRequest;
use App\Models\Contact;

class ContactController extends Controller
{
    public function create()
    {
        return view('front.contact');
    }

    public function store(ContactRequest $request)
    {
        if($request->use()){
            $request->merge([
                'user_id'   => $request->user()->id,
                'name'      => $request->user()->name,
                'email'     => $request->user()->email
            ]);
        }

        Contact::create ($request->all());

        return bach()->with('status', __('Your message has been recorded, we will respond as soon as possible.'));
    }
}

app/Http/Controllers/Front/PageController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Models\Page;

class PageController extends Controller
{
    public function __invoke(Page $page)
    {
        return view('front.page', compact('page'));
    }
}

app/Http/Controllers/Front/PostController.php
<?php
namespace App\Http\Controllers\Front;
use App\Repositories\PostRepository;
use App\Http\Controllers\Controller;
use App\Models\{ Category, User, Tag };
use App\Http\Requests\Front\SearchRequest;
use Illuminate\Http\Request;


class PostController extends Controller
{
    protected $postRepository;
    protected $nbrPages;


    public function __construct(PostRepository $postRepository)
    {
        $this->postRepository = $postRepository; ///SUPER MEGA IMPORTANT
        $this->nbrPages = config('app.nbrPages.posts');
    }

    public function index()
    {
        $posts = $this->postRepository->getActiveOrderByDate($this->nbrPages);
        $heros = $this->postRepository->getHeros();
        return view('front.index', compact('posts', 'heros'));
    }

    public function show(Request $request, $slug)
    {
        $post = $this->postRepository->getPostBySlug($slug);
        return view('front.post', compact('post'));
    }


    public function category(Category $category)
    {
        $posts = $this->postRepository->getActiveOrderByDateForCategory($this->nbrPages, $category->slug);
        $title = __('Posts for category ') . '<strong>' . $category->title . '</strong>';
        return view('front.index', compact('posts', 'title'));
    }

    public function user(User $user){
        $posts = $this->postRepository->getActiveOrderByDateForUser($this->nbrPages, $user->id);
        $title = __('Posts by author') . '<strong>' . $user->name . '<strong>';
        return view('front.index', compact('posts', 'title'));
    }

    public function tag(Tag $tag)
    {
        $posts = $this->postRepository->getActiveOrderByDateForTag($this->nbrPages, $tag->slug);
        $title = __('Posts for tag ') . '<strong>' . $tag->tag . '</strong>';
        return view('front.index', compact('posts', 'title'));
    }

    public function search(SearchRequest $request)
    {
        $search = $request->search;
        $posts = $this->postRepository->search($this->nbrPages, $search);
        $title = __('Posts found with search: ') . '<strong>' . $search . '</strong>';

        return view('front.index', compact('posts', 'title'));
    }
}

resources/views/front/comments.blade.php
<h3>
  @lang('Comments')
  @if (Auth::guest())
    <span>@lang('You must be connected to add a comment or reply.')</span>      
  @endif
</h3>
<!-- Commentlist -->
<ol class="commentlist">
  <x-front.comments :comments="$comments"/>
</ol>

resources/views/front/contact.blade.php
@extends('front.layout')

@section('main')

    <div class="row">
        <div class="column large-12">

            <div class="s-content__entry-header">
                <h1 class="s-content__title">@lang('Get In Touch With Us')</h1>
            </div>

            <div class="row row-x-center">
                <div class="column large-6 tab-12">

                  <!-- Session Status -->
                  <x-auth.session-status :status="session('status')" />

                  <!-- Validation Errors -->
                  <x-auth.validation-errors :errors="$errors" />

                  <form class="s-content__form" method="post" action="{{ route('contacts.store') }}">
                      @csrf
                      <fieldset>

                          @if(Auth::guest())
                              <!-- Name -->
                              <div>
                                <label for="name">@lang('Name')</label>  
                                <input 
                                    id="name" 
                                    class="h-full-width" 
                                    type="text" 
                                    name="name" 
                                    placeholder="@lang('Your name')" 
                                    value="{{ old('name') }}" 
                                    required 
                                    autofocus>
                              </div>

                              <!-- Email Address -->
                              <x-auth.input-email />
                          @endif

                          <!-- Message -->                          
                          <label for="message">@lang('Your Message')</label> 
                          <textarea name="message" id="message" class="h-full-width" placeholder="@lang('Your Message')" required>{{ old('message') }}</textarea>                          

                          <br>
                          <x-auth.submit title="Send" />

                      </fieldset>
                  </form>

                </div>
            </div>


        </div>
    </div>

@endsection

resources/views/front/index.blade.php
@extends('front.layout')

@section('hero')

    @isset($heros)

        <section id="hero" class="s-hero">

          <div class="s-hero__slider">

              @foreach($heros as $hero)
                  <x-front.hero :post="$hero" />
              @endforeach

          </div>

          <div class="s-hero__social hide-on-mobile-small">
              <p>@lang('Follow')</p>
              <span></span>
              <ul class="s-hero__social-icons">
                  @foreach ($follows as $follow)
                    <li>
                        <a href="{{ $follow->href }}">
                            <i 
                                class="fab fa-{{ $follow->title === 'Facebook' ? 'facebook-f' : lcfirst($follow->title) }}" 
                                aria-hidden="true">
                            </i>
                        </a>
                    </li>
                  @endforeach
              </ul>
          </div>

          <div class="nav-arrows s-hero__nav-arrows">
              <button class="s-hero__arrow-prev">
                  <svg viewBox="0 0 15 15" xmlns="http://www.w3.org/2000/svg" width="15" height="15"><path d="M1.5 7.5l4-4m-4 4l4 4m-4-4H14" stroke="currentColor"></path></svg>
              </button>
              <button class="s-hero__arrow-next">
                <svg viewBox="0 0 15 15" xmlns="http://www.w3.org/2000/svg" width="15" height="15"><path d="M13.5 7.5l-4-4m4 4l-4 4m4-4H1" stroke="currentColor"></path></svg>
              </button>
          </div>

        </section>

    @endisset

@endsection

@section('main')

    @isset($title)
        <div class="row">
            <div class="column">
                <h1>{!! $title !!}</h1>
            </div>
        </div>
    @endisset

    <div class="s-bricks">

      <div class="masonry">
          <div class="bricks-wrapper h-group">

              <div class="grid-sizer"></div>

              <div class="lines">
                  <span></span>
                  <span></span>
                  <span></span>
              </div>

              @foreach($posts as $post)

                  <x-front.brick :post="$post" />

              @endforeach

            </div>

      </div>

      <div class="row">
          <div class="column large-12">
              {{ $posts->links('front.pagination') }}
          </div>
      </div>

  </div>

@endsection

resources/views/front/layout.blade.php
<!DOCTYPE html>
<html class="no-js" lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="author" content="">

    <!--- Custom page needs
    ================================================== -->
    <title>{{ isset($post) && $post->seo_title ? $post->seo_title :  config('app.name') }}</title>
    
    <meta name="description" content="{{ isset($post) && $post->meta_description ? $post->meta_description : __(config('app.description')) }}">
    <meta name="author" content="{{ isset($post) ? $post->user->name : __(config('app.author')) }}">
    @if(isset($post) && $post->meta_keywords)
        <meta name="keywords" content="{{ $post->meta_keywords }}">
    @endif

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{{ asset('css/vendor.css') }}">
    <link rel="stylesheet" href="{{ asset('css/styles.css') }}">
    @yield('style')

    <!-- script
    ================================================== -->
    <script src="{{ asset('js/modernizr.js') }}"></script>
    <script defer src="{{ asset('js/fontawesome/all.min.js') }}"></script>

    <!-- favicons
    ================================================== -->
    <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('favicon-16x16.png') }}">
    <link rel="manifest" href="{{ asset('site.webmanifest') }}">

</head>




<body id="top">


    <!-- preloader
    ================================================== -->
    <div id="preloader"> 
    	<div id="loader"></div>
    </div>


    <!-- header
    ================================================== -->
    <header class="s-header @unless(currentRoute('home')) s-header--opaque @endunless">
        <div class="s-header__logo">
            <a class="logo" href="{{ route('home') }}">
                <img src="{{ asset('images/logo.svg') }}" alt="Homepage">
            </a>
        </div>
        <div class="row s-header__navigation">
            <nav class="s-header__nav-wrap">
                <h3 class="s-header__nav-heading h6">@lang('Navigate to')</h3>
                <ul class="s-header__nav">
                    <li {{ currentRoute('home') }}>
                        <a href="{{ route('home') }}" title="">@lang('Home')</a>
                    </li>
                    <li class="has-children">
                        <a href="#" title="">@lang('Categories')</a>
                        <ul class="sub-menu">
                            @foreach($categories as $category)
                                <li><a href="{{ route('category', $category->slug) }}">{{ $category->title }}</a></li>
                            @endforeach
                        </ul>
                    </li>
                    <li {{ currentRoute('contacts.create') }}>
                        <a href="{{ route('contacts.create') }}" title="">@lang('Contact')</a>
                    </li>
                    @guest
                        @request('register')
                            <li class="current">
                                <a href="{{ request()->url() }}">@lang('Register')</a>
                            </li>
                        @endrequest
                        @request('forgot-password')
                            <li class="current">
                                <a href="{{ request()->url() }}">@lang('Password')</a>
                            </li>
                        @endrequest
                        @request('reset-password/*')
                            <li class="current">
                                <a href="{{ request()->url() }}">@lang('Password')</a>
                            </li>
                        @endrequest
                        <li {{ currentRoute('login') }}>
                            <a href="{{ route('login') }}">@lang('Login')</a>
                        </li>
                    @else
                        <li>                                
                            <form action="{{ route('logout') }}" method="POST" hidden>
                                @csrf                                
                            </form>
                            <a 
                                href="{{ route('logout') }}"
                                onclick="event.preventDefault(); this.previousElementSibling.submit();">
                                @lang('Logout')
                            </a>
                        </li>
                    @endguest
                </ul>
                <a href="#0" title="@lang('Close Menu')" class="s-header__overlay-close close-mobile-menu">@lang('Close')</a>
            </nav>
        </div>
        <a class="s-header__toggle-menu" href="#0" title="@lang('Menu')"><span>@lang('Menu')</span></a>
        <div class="s-header__search">
            <div class="s-header__search-inner">
                <div class="row wide">
                    <form role="search" method="get" class="s-header__search-form" action="{{ Route('posts.search') }}">
                        <label>
                            <span class="h-screen-reader-text">@lang('Search for:')</span>
                            <input id="search" type="search" name="search" class="s-header__search-field" placeholder="@lang('Search for...')" title="@lang('Search for:')" autocomplete="off">                        
                        </label>
                        <input type="submit" class="s-header__search-submit" value="Search"> 
                    </form>
                    <a href="#0" title="@lang('Close Search')" class="s-header__overlay-close">@lang('Close')</a>
                </div>
            </div>
        </div>
        <a class="s-header__search-trigger" href="#">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 17.982 17.983"><path fill="#010101" d="M12.622 13.611l-.209.163A7.607 7.607 0 017.7 15.399C3.454 15.399 0 11.945 0 7.7 0 3.454 3.454 0 7.7 0c4.245 0 7.699 3.454 7.699 7.7a7.613 7.613 0 01-1.626 4.714l-.163.209 4.372 4.371-.989.989-4.371-4.372zM7.7 1.399a6.307 6.307 0 00-6.3 6.3A6.307 6.307 0 007.7 14c3.473 0 6.3-2.827 6.3-6.3a6.308 6.308 0 00-6.3-6.301z"/></svg>
        </a>
    </header>


    <!-- hero dans front.index
    ================================================== -->
    @yield('hero')


    <!-- content
    ================================================== -->
    <section class="s-content @if(currentRoute('home')) s-content--no-top-padding @endif">

        @yield('main')

    </section>


    <!-- footer
    ================================================== -->
    <footer class="s-footer">

        <div class="s-footer__main">
    
            <div class="row">
    
                <div class="column large-6 medium-6 tab-12 s-footer__info">
    
                    <h5>@lang('About Our Site')</h5>
    
                    <p>
                    Lorem ipsum Ut velit dolor Ut labore id fugiat in ut 
                    fugiat nostrud qui in dolore commodo eu magna Duis 
                    cillum dolor officia esse mollit proident Excepteur 
                    exercitation nulla. Lorem ipsum In reprehenderit 
                    commodo aliqua irure.
                    </p>
    
                </div>
    
                <div class="column large-3 medium-3 tab-6 s-footer__site-links">
    
                    <h5>@lang('Site Links')</h5>
    
                    <ul>
                        @foreach($pages as $page)
                            <li><a href="{{ route('page', $page->slug) }}">@lang($page->title)</a></li>
                        @endforeach
                    </ul>
    
                </div> 
    
                <div class="column large-2 medium-3 tab-6 s-footer__social-links">
    
                    <h5>Follow Us</h5>
    
                    <ul>
                        @foreach ($follows as $follow)
                        <li>
                            <a href="{{ $follow->href }}">{{ $follow->title }}</a>
                        </li>
                        @endforeach
                    </ul>
    
                </div>
    
            </div>
    
        </div>
    
        <div class="s-footer__bottom">
            <div class="row">
                <div class="column">
                    <div class="ss-copyright">
                        <span>© Copyright Calvin 2020</span> 
                        <span>Design by <a href="https://www.styleshout.com/">StyleShout</a></span>
                    </div>
                </div>
            </div> 
    
            <div class="ss-go-top">
                <a class="smoothscroll" title="Back to Top" href="#top">
                    <svg viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" width="15" height="15"><path d="M7.5 1.5l.354-.354L7.5.793l-.354.353.354.354zm-.354.354l4 4 .708-.708-4-4-.708.708zm0-.708l-4 4 .708.708 4-4-.708-.708zM7 1.5V14h1V1.5H7z" fill="currentColor"></path></svg>
                </a>
            </div>
        </div>
    
    </footer> 
    <!-- end s-footer -->


    <!-- JavaScript
    ================================================== -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="{{ asset('js/plugins.js') }}"></script>
    <script src="{{ asset('js/main.js') }}"></script>
    @yield('scripts')

</body>

</html>

resources/views/front/page.blade.php
@extends('front.layout')

@section('main')

    <div class="row">
        <div class="column large-12">

          <article class="s-content__entry">

            <div class="s-content__entry-header">
                <h1 class="s-content__title">@lang($page->title)</h1>
            </div>

            <div class="s-content__primary">

                <div class="s-content__page-content">

                    {!! $page->body !!}

                </div>

            </div>
        </article>

        </div>
    </div>

@endsection

resources/views/front/pagination.blade.php
@if ($paginator->hasPages())
    <nav class="pgn">
        <ul>
            {{-- Previous Page Link --}}
            <li>
                @if ($paginator->onFirstPage())
                    <span class="pgn__prev inactive" href="#0">@lang('Prev')</span>
                @else
                    <a href="{{ $paginator->previousPageUrl() }}" class="pgn__prev" rel="prev">@lang('Prev')</a>
                @endif
            </li>

            {{-- Pagination Elements --}}
            @foreach ($elements as $element)

                {{-- "Three Dots" Separator --}}
                @if (is_string($element))
                    <li><span class="pgn__num current">{{ $element }}</span></li>
                @endif

                {{-- Array Of Links --}}
                @if (is_array($element))
                    @foreach ($element as $page => $url)
                        <li>
                            @if ($page == $paginator->currentPage())
                                <span class="pgn__num current">{{ $page }}</span>
                            @else
                                <a href="{{ $url }}" class="pgn__num">{{ $page }}</a>
                            @endif
                        </li>
                    @endforeach
                @endif

            @endforeach

            {{-- Next Page Link --}}
            <li>
                @if ($paginator->hasMorePages())
                    <a href="{{ $paginator->nextPageUrl() }}"  class="pgn__next" rel="next">@lang('Next')</a>
                @else
                    <span class="pgn__next inactive">@lang('Next')</span>
                @endif
            </li>
        </ul>
    </nav>
@endif